/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'irfn' at '2/6/16 7:48 PM' with Gradle 2.12
 *
 * @author irfn, @date 2/6/16 7:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
